# Generated by Django 6.0.2 on 2026-02-17 14:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('category', models.CharField(choices=[('core', 'Core'), ('optional', 'Optional (risk-based)')], default='core', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('applicable_species', models.ManyToManyField(related_name='vaccines', to='vaccines.species')),
            ],
        ),
        migrations.CreateModel(
            name='RecommendationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dose_number', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('due_age_weeks', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(400)])),
                ('due_age_months', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(240)])),
                ('repeat_every_months', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)])),
                ('requires_outdoor', models.BooleanField(default=False)),
                ('requires_travel', models.BooleanField(default=False)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='vaccines.species')),
                ('vaccine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='vaccines.vaccine')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('vaccine', 'species', 'dose_number'), name='uniq_rule_vaccine_species_dose')],
            },
        ),
    ]
