# Generated by Django 6.0.2 on 2026-02-17 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('species', models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat')], max_length=10)),
                ('birth_date', models.DateField()),
                ('lifestyle', models.CharField(choices=[('indoor', 'Indoor'), ('outdoor', 'Outdoor'), ('mixed', 'Mixed')], default='mixed', max_length=10)),
                ('travels_abroad', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
    ]
