# Generated by Django 6.0.2 on 2026-04-03 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_pet_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Medical Conditions',
            },
        ),
        migrations.AlterModelOptions(
            name='pet',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='pet',
            name='medical_conditions',
            field=models.ManyToManyField(blank=True, related_name='pets', to='pets.medicalcondition'),
        ),
    ]
