# Generated by Django 6.0.3 on 2026-04-05 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_create_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_vet',
            field=models.BooleanField(default=False, help_text='Designates whether this user has veterinary administrative privileges.', verbose_name='Is Veterinarian'),
        ),
    ]
