# Generated by Django 6.0.2 on 2026-02-17 14:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pets', '0001_initial'),
        ('vaccines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_start_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('final', 'Final')], default='draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='pets.pet')),
            ],
        ),
        migrations.CreateModel(
            name='Dose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dose_number', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('due_date', models.DateField()),
                ('is_booster', models.BooleanField(default=False)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('vaccine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doses', to='vaccines.vaccine')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doses', to='planner.plan')),
            ],
            options={
                'ordering': ['due_date', 'vaccine__name'],
                'constraints': [models.UniqueConstraint(fields=('plan', 'vaccine', 'dose_number'), name='uniq_dose_plan_vaccine_number')],
            },
        ),
    ]
